# Generated by Django 3.2.4 on 2021-06-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
